# Generated by Django 5.1 on 2024-08-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="문정현", max_length=10),
            preserve_default=False,
        ),
    ]
