# Generated by Django 5.1 on 2024-08-25 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_topic",
                    models.CharField(max_length=50, verbose_name="메인 주제"),
                ),
                (
                    "sub_topic",
                    models.CharField(max_length=50, verbose_name="서브 주제"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(max_length=100, verbose_name="단어"),
        ),
        migrations.AlterField(
            model_name="word",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="words",
                to="words.topic",
            ),
        ),
    ]
