# Generated by Django 5.1 on 2024-08-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0003_alter_word_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="word",
            unique_together=set(),
        ),
    ]
