# Generated by Django 5.1 on 2024-08-27 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0004_alter_word_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentence",
            name="word",
        ),
        migrations.AddField(
            model_name="sentence",
            name="word",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sentences",
                to="words.word",
            ),
        ),
    ]
